"""What the application layer needs of the vault's writer and history.

The concrete classes are ``coffer.infrastructure.vault.writer.VaultWriter``
and ``coffer.infrastructure.vault.repository.VaultRepository``, wired at the
composition root; these Protocols are the part a use case may depend on.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable, Sequence
from contextlib import AbstractContextManager
from typing import Any, Protocol

from coffer.domain.vault.findings import Finding
from coffer.domain.vault.history import Commit
from coffer.domain.vault.writers import CommitMeta
from coffer.domain.vault.writes import CommitResult, Expect, Listener, Snapshot, Validator


class TransactionPort(Protocol):
    meta: CommitMeta
    paths: list[str]
    version: str | None

    def read(self, path: str) -> Snapshot: ...
    def touch(self, path: str) -> None: ...
    def write(self, path: str, data: bytes, expected: str | Expect | None = ...) -> None: ...
    def delete(self, path: str, expected: str | Expect | None = ...) -> None: ...
    def commit(self, meta: CommitMeta | None = None) -> str | None: ...
    def abort(self) -> None: ...
    def __enter__(self) -> TransactionPort: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...


class VaultWriterPort(Protocol):
    @property
    def lock(self) -> AbstractContextManager[Any]:
        """The vault's one write lock (a re-entrant lock); a sync checkout holds it."""
        ...

    def begin(self, meta: CommitMeta) -> TransactionPort: ...
    def read_disk(self, path: str) -> bytes | None: ...
    def write_file(
        self, path: str, data: bytes, *, meta: CommitMeta, expected: str | Expect | None = ...
    ) -> str | None: ...
    def delete_file(
        self, path: str, *, meta: CommitMeta, expected: str | Expect | None = ...
    ) -> str | None: ...
    def settle(
        self, paths: Sequence[str] | None = None, *, meta: CommitMeta | None = None
    ) -> CommitResult | None: ...
    def problems(self) -> dict[str, tuple[Finding, ...]]: ...
    def set_validator(self, validator: Validator) -> None: ...
    @property
    def validator(self) -> Validator: ...
    def add_listener(self, listener: Listener) -> None: ...
    def notify(self, result: CommitResult) -> None: ...
    def set_held(self, provider: Callable[[], Iterable[str]]) -> None: ...
    def held(self) -> frozenset[str]: ...
    def restore_disk(self, path: str, data: bytes | None) -> None: ...


class VaultHistoryPort(Protocol):
    def head(self) -> str | None: ...
    def read(self, ref: str, path: str) -> bytes | None: ...
    def tree(self, ref: str = "HEAD", prefix: str = "") -> dict[str, str]: ...
    def log(
        self, *pathspecs: str, start: str | None = None, limit: int | None = None, skip: int = 0
    ) -> list[Commit]: ...
    def commit_of(self, version: str) -> Commit | None: ...
    def diff(self, version: str, path: str) -> str: ...
    def later(self, version: str, path: str) -> str | None: ...


__all__ = ["TransactionPort", "VaultHistoryPort", "VaultWriterPort"]
