"""What a thin sync round needs from the outside world
(ADR sync-applies-clean-merges-and-stops-on-any-conflict).

Every port here is synchronous except the history and the token: a round's
git work runs in one worker thread, start to finish, so that the checkout can
hold the vault's write lock without an event loop in between.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Protocol

from coffer.domain.sync.remote import SyncRemote
from coffer.domain.sync.rounds import RoundRecord
from coffer.domain.sync.stops import ConflictFile, Stop
from coffer.domain.vault.history import Commit
from coffer.domain.vault.trees import MergeResult, TreeChange
from coffer.domain.vault.writers import CommitMeta


class SyncGitPort(Protocol):
    """The vault repository, as a sync round uses it."""

    def ensure(self) -> None: ...
    def head(self) -> str | None: ...
    def set_remote(self, url: str, username: str | None = None) -> None: ...
    def clear_remote(self) -> None: ...
    def set_carry_secret(self, carry: bool) -> None: ...
    def fetch(self, branch: str, token: str | None) -> str | None: ...
    def push(self, commit: str, branch: str, token: str | None) -> None: ...
    def remote_tip(self, branch: str) -> str | None: ...
    def merge_base(self, a: str, b: str) -> str | None: ...
    def is_ancestor(self, a: str, b: str) -> bool: ...
    def tree_of(self, commit: str) -> str: ...
    def merge(self, ours: str, theirs: str, *, base: str | None = None) -> MergeResult: ...
    def diff(self, a: str | None, b: str) -> list[TreeChange]: ...
    def renames(self, a: str, b: str) -> list[tuple[str, str]]: ...
    def files(self, commit_or_tree: str, prefix: str = "") -> dict[str, str]: ...
    def read(self, ref: str, path: str) -> bytes | None: ...
    def blobs(self, blobs: Sequence[str]) -> dict[str, bytes]: ...
    def hash(self, data: bytes) -> str: ...
    def build_tree(self, base_tree: str, overrides: Mapping[str, str | None]) -> str: ...
    def commit_tree(self, tree: str, parents: tuple[str, ...], meta: CommitMeta) -> str: ...
    def checkout(self, old: str, new: str) -> None: ...
    def log(
        self, *pathspecs: str, start: str | None = None, limit: int | None = None
    ) -> list[Commit]: ...
    def commits_between(self, since: str | None, until: str) -> list[Commit]: ...
    def new_blobs(self, since: str | None, until: str) -> list[tuple[str, str]]: ...
    def snapshot(self, commit: str) -> str: ...
    def snapshots(self) -> list[tuple[str, str, int]]: ...
    def merge_file(
        self, ours: bytes, base: bytes, theirs: bytes, labels: tuple[str, str]
    ) -> bytes: ...


class RoundStatePort(Protocol):
    """``local/sync/round.json``: the stop waiting for a person, the join
    choices still open, a hold's confirmation, and the blobs a person said to
    push although they looked like a plaintext secret."""

    def stop(self) -> Stop | None: ...
    def set_stop(self, stop: Stop | None) -> None: ...
    def join_choices(self) -> tuple[ConflictFile, ...]: ...
    def set_join_choices(self, choices: Sequence[ConflictFile]) -> None: ...
    def confirmed(self) -> tuple[str, str] | None: ...
    def set_confirmed(self, pair: tuple[str, str] | None) -> None: ...
    def joined(self) -> bool: ...
    def set_joined(self, joined: bool) -> None: ...
    def plaintext_allowed(self) -> frozenset[str]: ...
    def allow_plaintext(self, blobs: Sequence[str]) -> None: ...


class RemoteStorePort(Protocol):
    """``local/sync/remote.json``."""

    def get(self) -> SyncRemote | None: ...
    def put(self, remote: SyncRemote) -> None: ...
    def clear(self) -> None: ...


class RoundHistoryPort(Protocol):
    """Every round this machine ran, in ``runs.db`` (spec vault-sync "Keep
    machine-local state out of the repository"): another machine's account of
    rounds this one never ran would mean nothing here."""

    async def append(self, record: RoundRecord) -> RoundRecord: ...
    async def recent(self, limit: int, offset: int = 0) -> list[RoundRecord]: ...
    async def get(self, round_id: int) -> RoundRecord | None: ...
    async def count(self) -> int: ...


class TokenPort(Protocol):
    async def token_for(self, remote: SyncRemote) -> str | None: ...


class ScratchPort(Protocol):
    """``derived/sync-conflicts/``: the marked-up copies a person edits to
    hand-merge a conflicting file. Never inside the vault, so no conflict
    marker ever reaches a vault file."""

    def write(self, path: str, data: bytes) -> str: ...
    def read(self, path: str) -> bytes | None: ...
    def where(self, path: str) -> str | None: ...
    def clear(self) -> None: ...


class MachinePort(Protocol):
    """This machine, and the descriptor it publishes under ``machines/``."""

    def machine_id(self) -> str: ...
    def label(self) -> str: ...
    def descriptor_path(self) -> str: ...
    def descriptor(self, *, last_round_at: str | None, last_commit: str | None) -> bytes: ...
    def labels(self, files: Mapping[str, bytes]) -> dict[str, str]: ...


__all__ = [
    "MachinePort",
    "RemoteStorePort",
    "RoundHistoryPort",
    "RoundStatePort",
    "ScratchPort",
    "SyncGitPort",
    "TokenPort",
]
