"""``CATALOG.md`` — a run's artifacts, rendered from the directory (FR-031).

The catalogue is **generated, never hand-maintained**: every line of it is a
fact read off ``artifacts/<node_key>/<attempt>/<name>`` by the artifact store,
so the file can be deleted at any moment and the next regeneration reproduces
it byte for byte. That property is the reason there is no "generated at" line
here — a clock in the header would make every regeneration a diff, and an
agent re-reading the catalogue between two nodes would see churn that means
nothing.

The store computes *what* the catalogue says; this module decides *how it
reads*, because how a catalogue lands in an agent's context is a question about
prompts rather than about storage. The one rule it enforces on top of the
store's ordering is its own sort, so two stores that list in different orders
still produce one document.
"""

from __future__ import annotations

from collections.abc import Iterable
from datetime import UTC

from coffer.application.workflow.ports import ArtifactEntry, ArtifactStorePort

__all__ = ["CATALOGUE_TITLE", "regenerate_catalogue", "render_catalogue"]

#: The file's own H1. Exported because the composer embeds the catalogue under
#: a heading of its own and strips this one rather than nesting an H1 inside an
#: H3, which reads to an agent as a new document starting mid-message.
CATALOGUE_TITLE = "# Artifact catalogue"

#: Said in the document itself, because the document travels into an agent's
#: context and the agent is the one that might otherwise try to edit it.
_PREAMBLE = (
    "Generated by Coffer from this run's artifact directory. Edits are overwritten; "
    "produce an artifact by writing the file, not by adding a row here."
)

_EMPTY = "No artifacts yet."

_COLUMNS = "| Artifact | Node | Attempt | Path | Size | Modified (UTC) |"
_RULE = "| --- | --- | --- | --- | --- | --- |"

#: ``ArtifactEntry.path`` is relative to the run's ``artifacts/`` directory;
#: the catalogue quotes it relative to the run directory instead, which is the
#: directory the run's own files are addressed from everywhere else.
_ARTIFACTS_PREFIX = "artifacts"


def render_catalogue(entries: Iterable[ArtifactEntry]) -> str:
    """The Markdown for ``CATALOG.md``, naming each artifact's node and attempt.

    Deterministic in its input: the same entries render the same bytes, and the
    entries are sorted here rather than trusted in arrival order (FR-031).
    """
    rows = sorted(entries, key=lambda e: (e.node_key, e.attempt, e.name))
    lines = [CATALOGUE_TITLE, "", _PREAMBLE, ""]
    if not rows:
        lines.append(_EMPTY)
    else:
        lines.extend([_COLUMNS, _RULE])
        lines.extend(
            "| `{name}` | `{node}` | {attempt} | `{path}` | {size} | {when} |".format(
                name=_cell(entry.name),
                node=_cell(entry.node_key),
                attempt=entry.attempt,
                path=_cell(f"{_ARTIFACTS_PREFIX}/{entry.path}"),
                size=_human_size(entry.size),
                when=_stamp(entry),
            )
            for entry in rows
        )
    return "\n".join(lines) + "\n"


def regenerate_catalogue(store: ArtifactStorePort, run_id: str) -> str:
    """Re-read the directory, re-render the catalogue, write it, and return it.

    The caller gets the text back because the composer needs the same string it
    just wrote, and reading the file again to obtain it would be one more way
    for the two to disagree.
    """
    markdown = render_catalogue(store.list_artifacts(run_id))
    store.write_catalogue(run_id, markdown)
    return markdown


def _cell(text: str) -> str:
    """A table cell that cannot break the table.

    Neither an artifact name nor a node key can legally contain a pipe today —
    both pass a segment guard that excludes it — but a catalogue is rendered
    from whatever is on disk, and "on disk" is not a guarantee this module
    holds.
    """
    return text.replace("|", "\\|")


def _stamp(entry: ArtifactEntry) -> str:
    """The artifact's mtime, in UTC, to the second.

    To the second rather than finer because the field is read by a human
    deciding which of two attempts is newer, and a microsecond tail buys them
    nothing while making the table wider.
    """
    return entry.modified_at.astimezone(UTC).strftime("%Y-%m-%d %H:%M:%S")


def _human_size(size: int) -> str:
    if size < 1024:
        return f"{size} B"
    value = float(size)
    for unit in ("KB", "MB", "GB"):
        value /= 1024.0
        if value < 1024.0:
            return f"{value:.1f} {unit}"
    return f"{value / 1024.0:.1f} TB"
