"""``coffer agent ...`` — registered AI agents.

``rm``, ``enable`` and ``disable`` are the lifecycle verbs every kind shares,
generated by ``_kind_verbs``. ``list``, ``show``, ``add`` and ``edit`` are
written here because an agent's record is served by its own routes
(``/agents``): the kind owns its lifecycle, so the generic config PATCH refuses
it, and the resolved config directory and model binding a person wants to read
are on ``AgentOut``, not on the raw resource document. ``show`` also carries the
derived ``coffer_connection`` — the agent's Coffer connection part by part, as
``GET /agents/{uid}/coffer-connection`` answers it (spec agent-registry "Manage
the agent lifecycle", "Report an agent's Coffer connection part by part").

The connection, config, plugin, transcript and model commands live in sibling
modules, attached below (backend file-size cap).

Every command takes the agent's NAME and resolves it once, through ``_resolve``,
to the uid the routes address (ADR resource-identity-is-an-immutable-uid).
"""

from __future__ import annotations

import json as _json
from typing import Any

import httpx
import typer
from rich.console import Console
from rich.table import Table

from coffer.surfaces.cli import _client as _cli_client
from coffer.surfaces.cli import agent_config_cmd as _config
from coffer.surfaces.cli import agent_connection_cmd as _connection
from coffer.surfaces.cli import agent_models_cmd as _models
from coffer.surfaces.cli import agent_plugin_cmd as _plugins
from coffer.surfaces.cli import agent_transcript_cmd as _transcripts
from coffer.surfaces.cli._kind_verbs import (
    KindVerbs,
    check_title_arg,
    label,
    register_kind_verbs,
    verbose_of,
)
from coffer.surfaces.cli._resolve import resolve_ref

app = typer.Typer(help="Manage registered AI agents")
_console = Console()

_NAME = typer.Argument(..., metavar="NAME", help="Agent name or uid")


def _record(resource: dict[str, Any], agent: dict[str, Any]) -> dict[str, Any]:
    """The agent's own record, with the kind-agnostic fields beside it."""
    return {
        **agent,
        "title": resource.get("title"),
        "enabled": resource.get("enabled", True),
    }


@app.command("list")
def list_cmd(
    ctx: typer.Context,
    output_json: bool = typer.Option(False, "--json", help="JSON output for scripts"),
) -> None:
    """List registered agents."""
    verbose = verbose_of(ctx)
    c, _info = _cli_client.client_or_exit()
    with c:
        r = c.get("/agents")
        _cli_client.check(r, verbose=verbose)
        res = c.get("/resources", params={"kind": "agent"})
        _cli_client.check(res, verbose=verbose)
    by_uid = {item["uid"]: item for item in res.json()["resources"]}
    items = [_record(by_uid.get(a["uid"], {}), a) for a in r.json()["items"]]
    if output_json:
        typer.echo(_json.dumps({"resources": items}, indent=2))
        return
    table = Table(title="Agents")
    for col in ("Name", "Type", "Enabled", "Config Dir"):
        table.add_column(col)
    for it in items:
        table.add_row(label(it), it["type"], "yes" if it["enabled"] else "no", it["config_dir"])
    _console.print(table)


@app.command("add")
def add(
    ctx: typer.Context,
    agent_type: str = typer.Argument(..., help="claude_code | codex"),
    name: str | None = typer.Option(
        None, "--name", "-n", help="Resource name (defaults to a per-type name, e.g. claude-code)."
    ),
    config_dir: str | None = typer.Option(
        None, "--config-dir", help="Override config directory (default: ~/.claude etc.)."
    ),
    title: str | None = typer.Option(None, "--title", help="Display title (≤80 chars)"),
    description: str | None = typer.Option(None, "--description"),
) -> None:
    """Register an agent.

    ``--name`` is optional — when omitted the daemon derives a stable
    per-type default (``claude_code`` → ``claude-code``).
    """
    verbose = verbose_of(ctx)
    body: dict[str, Any] = {
        "type": agent_type,
        "config_dir": config_dir,
        "description": description,
    }
    # Only send `name` when provided so the server applies its per-type default.
    if name is not None:
        body["name"] = name
    check_title_arg(title)
    c, _info = _cli_client.client_or_exit()
    with c:
        r = c.post("/agents", json=body)
        _cli_client.check(r, verbose=verbose)
        registered = r.json().get("name", name) if r.content else name
        if title:
            t = c.patch(f"/resources/{r.json()['uid']}", json={"title": title})
            _cli_client.check(t, verbose=verbose)
    typer.echo(f"registered: agent {registered}")


def _optional_read(c: httpx.Client, path: str, **kw: Any) -> tuple[Any, str | None]:
    """A derived state's read: its body, or ``None`` and why it has none (a
    switched-off feature, a type with no such surface)."""
    r = c.get(path, **kw)
    if r.status_code == 200:
        return r.json(), None
    try:
        return None, str(r.json()["error"]["message"])
    except Exception:
        return None, f"HTTP {r.status_code}"


def _connection_state(c: httpx.Client, uid: str) -> tuple[dict[str, Any] | None, str | None]:
    """The agent's Coffer connection as GET /coffer-connection reports it, or
    ``None`` and why it could not be read."""
    return _optional_read(c, f"/agents/{uid}/coffer-connection")


@app.command("show")
def show(
    ctx: typer.Context,
    ref: str = _NAME,
    output_json: bool = typer.Option(False, "--json", help="JSON output for scripts"),
) -> None:
    """Show one agent, with its Coffer connection part by part."""
    verbose = verbose_of(ctx)
    c, _info = _cli_client.client_or_exit()
    with c:
        resource = resolve_ref(c, "agent", ref, verbose=verbose)
        r = c.get(f"/agents/{resource['uid']}")
        _cli_client.check(r, verbose=verbose)
        conn, conn_why = _connection_state(c, resource["uid"])
    data = {**_record(resource, r.json()), "coffer_connection": conn}
    if output_json:
        typer.echo(_json.dumps(data, indent=2))
        return
    typer.echo(label(data))
    for k in ("name", "title", "uid", "type", "config_dir", "description"):
        if k in ("name", "uid", "type", "config_dir") or data.get(k):
            typer.echo(f"{k}: {data[k]}")
    typer.echo(f"enabled: {'yes' if data['enabled'] else 'no'}")
    # "(unbound)" is a real state, not a missing value: an unbound agent runs
    # on its own default model.
    for k in ("model", "fast_model", "wire_api"):
        typer.echo(f"{k}: {data.get(k) or '(unbound)'}")
    if conn is None:
        typer.echo("coffer_connection: " + (f"unknown ({conn_why})" if conn_why else "unknown"))
    else:
        typer.echo(f"coffer_connection: {_connection.state_label(conn['state'])}")
        _connection.echo_parts(conn)


@app.command("edit")
def edit(
    ctx: typer.Context,
    ref: str = _NAME,
    new_name: str | None = typer.Option(None, "--name", help="New name"),
    title: str | None = typer.Option(
        None, "--title", help="Display title (≤80 chars); empty clears it"
    ),
    description: str | None = typer.Option(None, "--description"),
    config_dir: str | None = typer.Option(None, "--config-dir"),
    model: str | None = typer.Option(None, "--model", help="Model this agent answers with"),
    fast_model: str | None = typer.Option(
        None, "--fast-model", help="Small/fast model slot (anthropic wire only)"
    ),
    clear_fast_model: bool = typer.Option(False, "--clear-fast-model", help="Unbind the fast slot"),
    wire_api: str | None = typer.Option(
        None, "--wire-api", help="Codex wire api; `responses` is the only value it still loads"
    ),
) -> None:
    """Change an agent's name, title, description, config dir or model binding.

    The model binding lives on the agent, not on the connection: an unbound
    agent projects no model and runs on its own default. A change here takes
    effect on disk the next time that agent's connection is activated
    (`coffer provider switch <name>`), which is what re-projects the config.

    \f
    Two routes: the agent's own fields go to ``PATCH /agents/{uid}`` (the
    generic config PATCH refuses a kind that owns its lifecycle), the name and
    title to ``PATCH /resources/{uid}`` — last, so a refused field leaves the
    name alone. ``--clear-fast-model`` sends an explicit null, which the route
    tells apart from an absent field.
    """
    if fast_model is not None and clear_fast_model:
        typer.echo("give either --fast-model or --clear-fast-model, not both", err=True)
        raise typer.Exit(2)
    agent_body: dict[str, Any] = {
        k: v
        for k, v in (
            ("config_dir", config_dir),
            ("description", description),
            ("model", model),
            ("fast_model", fast_model),
            ("wire_api", wire_api),
        )
        if v is not None
    }
    if clear_fast_model:
        agent_body["fast_model"] = None
    resource_body = {k: v for k, v in (("name", new_name), ("title", title)) if v is not None}
    if not agent_body and not resource_body:
        typer.echo("nothing to change: name at least one option", err=True)
        raise typer.Exit(2)
    verbose = verbose_of(ctx)
    c, _info = _cli_client.client_or_exit()
    with c:
        current = resolve_ref(c, "agent", ref, verbose=verbose)
        shown = label(current)
        if agent_body:
            r = c.patch(f"/agents/{current['uid']}", json=agent_body)
            _cli_client.check(r, verbose=verbose)
        if resource_body:
            r = c.patch(f"/resources/{current['uid']}", json=resource_body)
            _cli_client.check(r, verbose=verbose)
            shown = label(r.json())
    typer.echo(f"updated: agent {shown}")


register_kind_verbs(
    app,
    KindVerbs(
        kind="agent",
        noun="agent",
        verbs=frozenset({"rm", "enable", "disable"}),
        help={
            "rm": "Remove an agent (re-discoverable by `coffer scan` — removal isn't permanent).",
            "enable": "Switch an agent back on: Coffer writes into and reads from it again.",
            "disable": "Switch an agent off: its delivered skills are reclaimed.",
        },
    ),
)


# --- sibling modules (backend file-size cap) ---------------------------------

_config.attach(app)
_connection.attach(app)
_plugins.attach(app)
_transcripts.attach(app)
_models.attach(app)
