"""``coffer agent ...`` — registered AI agents.

``rm``, ``enable`` and ``disable`` are the lifecycle verbs every kind shares,
generated by ``_kind_verbs``. ``list``, ``show``, ``add`` and ``edit`` are
written here because an agent's record is served by its own routes
(``/agents``): the kind owns its lifecycle, so the generic config PATCH refuses
it, and the resolved config directory and model binding a person wants to read
are on ``AgentOut``, not on the raw resource document. ``show`` also carries the
derived ``coffer_connection`` — the agent's Coffer connection part by part, as
``GET /agents/{uid}/coffer-connection`` answers it (spec agent-registry "Manage
the agent lifecycle", "Report an agent's Coffer connection part by part").

The connection, config, plugin, transcript and model commands live in sibling
modules, attached below (backend file-size cap).

There is one agent per type and it is named by the type (spec agent-registry
"Keep one agent per type, named by it"), so every command takes the TYPE —
``claude-code`` or ``codex`` (``claude_code`` also reads) — and resolves it
once, through ``_resolve``, to the uid the routes address (ADR
resource-identity-is-an-immutable-uid). A uid is accepted too.
"""

from __future__ import annotations

import json as _json
from typing import Any

import httpx
import typer
from rich.console import Console
from rich.table import Table

from coffer.surfaces.cli import _client as _cli_client
from coffer.surfaces.cli import agent_config_cmd as _config
from coffer.surfaces.cli import agent_connection_cmd as _connection
from coffer.surfaces.cli import agent_hooks_cmd as _hooks
from coffer.surfaces.cli import agent_models_cmd as _models
from coffer.surfaces.cli import agent_plugin_cmd as _plugins
from coffer.surfaces.cli import agent_transcript_cmd as _transcripts
from coffer.surfaces.cli._kind_verbs import (
    KindVerbs,
    register_kind_verbs,
    verbose_of,
)
from coffer.surfaces.cli._options import ExitCode
from coffer.surfaces.cli._resolve import resolve_ref

app = typer.Typer(help="Manage registered AI agents")
_console = Console()

_NAME = typer.Argument(..., metavar="TYPE", help="Agent type (claude-code | codex) or uid")


def _record(resource: dict[str, Any], agent: dict[str, Any]) -> dict[str, Any]:
    """The agent's own record, with the kind-agnostic ``enabled`` beside it."""
    return {**agent, "enabled": resource.get("enabled", True)}


@app.command("list")
def list_cmd(
    ctx: typer.Context,
    output_json: bool = typer.Option(False, "--json", help="JSON output for scripts"),
) -> None:
    """List registered agents."""
    verbose = verbose_of(ctx)
    c, _info = _cli_client.client_or_exit()
    with c:
        r = c.get("/agents")
        _cli_client.check(r, verbose=verbose)
        res = c.get("/resources", params={"kind": "agent"})
        _cli_client.check(res, verbose=verbose)
    by_uid = {item["uid"]: item for item in res.json()["resources"]}
    items = [_record(by_uid.get(a["uid"], {}), a) for a in r.json()["items"]]
    if output_json:
        typer.echo(_json.dumps({"resources": items}, indent=2))
        return
    table = Table(title="Agents")
    for col in ("Type", "Agent", "Enabled", "Config Dir"):
        table.add_column(col)
    for it in items:
        table.add_row(
            it["name"], it["display_name"], "yes" if it["enabled"] else "no", it["config_dir"]
        )
    _console.print(table)


@app.command("add")
def add(
    ctx: typer.Context,
    agent_type: str = typer.Argument(..., metavar="TYPE", help="claude-code | codex"),
    config_dir: str | None = typer.Option(
        None, "--config-dir", help="Config directory other than the standard one (~/.claude etc.)."
    ),
) -> None:
    """Register the agent of TYPE — one per type, named by it.

    Without ``--config-dir`` it is registered at the type's standard
    directory; an agent installed but never run gets that directory created.
    To move a registered agent, use ``coffer agent edit TYPE --config-dir``.
    """
    verbose = verbose_of(ctx)
    body: dict[str, Any] = {"type": agent_type.replace("-", "_"), "config_dir": config_dir}
    c, _info = _cli_client.client_or_exit()
    with c:
        r = c.post("/agents", json=body)
        _cli_client.check(r, verbose=verbose)
    typer.echo(f"registered: agent {r.json()['name']}")


def _optional_read(c: httpx.Client, path: str, **kw: Any) -> tuple[Any, str | None]:
    """A derived state's read: its body, or ``None`` and why it has none (a
    switched-off feature, a type with no such surface)."""
    r = c.get(path, **kw)
    if r.status_code == 200:
        return r.json(), None
    try:
        return None, str(r.json()["error"]["message"])
    except Exception:
        return None, f"HTTP {r.status_code}"


def _connection_state(c: httpx.Client, uid: str) -> tuple[dict[str, Any] | None, str | None]:
    """The agent's Coffer connection as GET /coffer-connection reports it, or
    ``None`` and why it could not be read."""
    return _optional_read(c, f"/agents/{uid}/coffer-connection")


@app.command("show")
def show(
    ctx: typer.Context,
    ref: str = _NAME,
    output_json: bool = typer.Option(False, "--json", help="JSON output for scripts"),
) -> None:
    """Show one agent, with its Coffer connection part by part."""
    verbose = verbose_of(ctx)
    c, _info = _cli_client.client_or_exit()
    with c:
        resource = resolve_ref(c, "agent", ref, verbose=verbose)
        r = c.get(f"/agents/{resource['uid']}")
        _cli_client.check(r, verbose=verbose)
        conn, conn_why = _connection_state(c, resource["uid"])
    data = {**_record(resource, r.json()), "coffer_connection": conn}
    if output_json:
        typer.echo(_json.dumps(data, indent=2))
        return
    typer.echo(data["display_name"])
    for k in ("name", "uid", "type", "config_dir"):
        typer.echo(f"{k}: {data[k]}")
    typer.echo(f"enabled: {'yes' if data['enabled'] else 'no'}")
    # "(unbound)" is a real state, not a missing value: an unbound agent runs
    # on its own default model.
    for k in ("model", "effort", "wire_api"):
        typer.echo(f"{k}: {data.get(k) or '(unbound)'}")
    tiers = data.get("tier_models") or {}
    typer.echo(
        "tier_models: "
        + (", ".join(f"{t}={m}" for t, m in tiers.items()) if tiers else "(unbound)")
    )
    if conn is None:
        typer.echo("coffer_connection: " + (f"unknown ({conn_why})" if conn_why else "unknown"))
    else:
        typer.echo(f"coffer_connection: {_connection.state_label(conn['state'])}")
        _connection.echo_parts(conn)
    if data.get("install_handoff"):
        typer.echo(f"hand off: coffer agent prompt {data['name']}  (its program is not found)")


@app.command("prompt")
def prompt(
    ctx: typer.Context,
    agent_type: str = typer.Argument(..., metavar="TYPE", help="claude-code | codex"),
    output_json: bool = typer.Option(False, "--json", help="JSON output for scripts"),
) -> None:
    """Print the prompt to give your agent to install TYPE's program.

    Offered while the program is not found, added or not — the same words the
    Agents page copies (spec agent-registry "Hand installing an agent's
    program to an agent").
    """
    wanted = agent_type.replace("_", "-")
    c, _info = _cli_client.client_or_exit()
    with c:
        r = c.get("/agents/types")
        _cli_client.check(r, verbose=verbose_of(ctx))
    row = next((t for t in r.json()["types"] if t["name"] == wanted), None)
    if row is None:
        typer.echo(f"unknown agent type: {agent_type} (claude-code | codex)", err=True)
        raise typer.Exit(int(ExitCode.INVALID_INPUT))
    if output_json:
        typer.echo(_json.dumps({"name": row["name"], "handoff": row["install_handoff"]}, indent=2))
        return
    if row["install_handoff"] is None:
        typer.echo(f"{row['name']} is installed; there is nothing to hand off.", err=True)
        raise typer.Exit(int(ExitCode.CONFLICT))
    typer.echo(row["install_handoff"]["prompt"])


@app.command("edit")
def edit(
    ctx: typer.Context,
    ref: str = _NAME,
    config_dir: str | None = typer.Option(
        None, "--config-dir", help="Use a different config directory"
    ),
    model: str | None = typer.Option(None, "--model", help="Model this agent answers with"),
    effort: str | None = typer.Option(None, "--effort", help="Reasoning effort level"),
    clear_effort: bool = typer.Option(False, "--clear-effort", help="Unbind the effort"),
    tier: list[str] | None = typer.Option(  # noqa: B008
        None,
        "--tier",
        help="Claude Code tier pin <tier>=<model> (opus, sonnet, haiku, fable); repeatable",
    ),
    clear_tiers: bool = typer.Option(False, "--clear-tiers", help="Unbind every tier pin"),
    wire_api: str | None = typer.Option(
        None, "--wire-api", help="Codex wire api; `responses` is the only value it still loads"
    ),
) -> None:
    """Change an agent's config directory or model binding.

    An agent's name is its type and it carries no title or description, so
    these are the whole of what can change. The model binding lives on the
    agent, not on the connection: an unbound agent projects no model and runs
    on its own default. A change here takes effect on disk the next time that
    agent's connection is activated (`coffer provider switch <name>`), which is
    what re-projects the config.

    \f
    One route, ``PATCH /agents/{uid}``. ``--clear-effort`` / ``--clear-tiers``
    send an explicit null, which the route tells apart from an absent field;
    ``--tier`` values are sent together as the whole mapping.
    """
    if effort is not None and clear_effort:
        typer.echo("give either --effort or --clear-effort, not both", err=True)
        raise typer.Exit(2)
    if tier and clear_tiers:
        typer.echo("give either --tier or --clear-tiers, not both", err=True)
        raise typer.Exit(2)
    tiers: dict[str, str] = {}
    for item in tier or []:
        name, sep, value = item.partition("=")
        if not sep or not name.strip() or not value.strip():
            typer.echo(f"--tier takes <tier>=<model>, got {item!r}", err=True)
            raise typer.Exit(2)
        tiers[name.strip()] = value.strip()
    agent_body: dict[str, Any] = {
        k: v
        for k, v in (
            ("config_dir", config_dir),
            ("model", model),
            ("effort", effort),
            ("wire_api", wire_api),
        )
        if v is not None
    }
    if clear_effort:
        agent_body["effort"] = None
    if tiers:
        agent_body["tier_models"] = tiers
    if clear_tiers:
        agent_body["tier_models"] = None
    if not agent_body:
        typer.echo("nothing to change: name at least one option", err=True)
        raise typer.Exit(2)
    verbose = verbose_of(ctx)
    c, _info = _cli_client.client_or_exit()
    with c:
        current = resolve_ref(c, "agent", ref, verbose=verbose)
        r = c.patch(f"/agents/{current['uid']}", json=agent_body)
        _cli_client.check(r, verbose=verbose)
    typer.echo(f"updated: agent {current['name']}")


register_kind_verbs(
    app,
    KindVerbs(
        kind="agent",
        noun="agent",
        verbs=frozenset({"rm", "enable", "disable"}),
        help={
            "rm": "Remove an agent (re-discoverable by `coffer scan` — removal isn't permanent).",
            "enable": "Switch an agent back on: Coffer writes into and reads from it again.",
            "disable": "Switch an agent off: its delivered skills are reclaimed.",
        },
    ),
)


# --- sibling modules (backend file-size cap) ---------------------------------

_config.attach(app)
_connection.attach(app)
_plugins.attach(app)
_transcripts.attach(app)
_models.attach(app)
_hooks.attach(app)
