"""``coffer mcp ...`` — MCP servers and their capabilities.

The lifecycle verbs (``list``, ``show``, ``edit``, ``rm``, ``enable``,
``disable``, ``scope``) are the ones every kind shares, generated by
``_kind_verbs`` from the ``mcp_server`` descriptor. What is left here is what
only an MCP server has: ``add`` (the transport is parsed from ``--stdio`` or
``--http``; ``edit`` takes the same transport flags, from ``_mcp_edit``),
``test`` (re-query the capabilities, then report health) and the
``cap`` group (``_mcp_caps.py``).

A server's name is fixed once registered, because it is the prefix of every
tool name an agent sees (spec mcp-gateway "Manage MCP servers as resources");
``edit --name`` is therefore refused by the daemon. A server has no display
title: its name and its description are all it carries.

Every command takes the server's NAME, because that is what a person knows; the
uid the daemon addresses it by is looked up once per command through
``_resolve`` (ADR resource-identity-is-an-immutable-uid).
"""

from __future__ import annotations

import shlex
from typing import Any

import httpx
import typer

from coffer.surfaces.cli import _client as _cli_client
from coffer.surfaces.cli._approvals import WAIT_OPTION, pending_for, settle
from coffer.surfaces.cli._kind_verbs import (
    DEFAULT_VERBS,
    Column,
    KindVerbs,
    register_kind_verbs,
    verbose_of,
)
from coffer.surfaces.cli._mcp_caps import cap_app
from coffer.surfaces.cli._mcp_edit import MCP_EDIT_FLAGS, parse_pairs
from coffer.surfaces.cli._resolve import resolve_uid

app = typer.Typer(help="Manage MCP servers and their capabilities")


def _parse_secrets(creds: list[str]) -> dict[str, str]:
    """Parse `--secret KEY=VALUE` repeatable into a dict."""
    return parse_pairs("--secret", creds, "SECRET_REF")


@app.command("add")
def add(
    ctx: typer.Context,
    name: str = typer.Argument(..., help="Server name (fixed once registered, ≤24 chars)"),
    stdio: str | None = typer.Option(
        None,
        "--stdio",
        help="Command line to launch, quoted as one string, e.g. 'npx -y my-server --flag'",
    ),
    http: str | None = typer.Option(None, "--http", help="HTTP MCP server URL"),
    secret: list[str] = typer.Option(  # noqa: B008
        [], "--secret", help="ENV_OR_HEADER=SECRET_REF (repeatable)"
    ),
    description: str | None = typer.Option(None, "--description"),
    wait: bool = WAIT_OPTION,
) -> None:
    """Register a new MCP server (stdio OR http; pick one).

    A --secret citing a secret that already goes somewhere else waits for
    approval in the Coffer app before the server receives it; the command says
    so and exits 9, or waits with --wait.
    """
    verbose = verbose_of(ctx)
    if (stdio is None) == (http is None):
        typer.echo("specify exactly one of --stdio or --http", err=True)
        raise typer.Exit(2)

    if stdio is not None:
        parts = shlex.split(stdio)
        if not parts:
            typer.echo("--stdio command cannot be empty", err=True)
            raise typer.Exit(2)
        transport: dict[str, Any] = {
            "type": "stdio",
            "command": parts[0],
            "args": parts[1:],
            "secret_refs": _parse_secrets(secret),
        }
    else:
        transport = {
            "type": "http",
            "url": http,
            "secret_refs": _parse_secrets(secret),
        }

    payload = {
        "kind": "mcp_server",
        "name": name,
        "description": description,
        "config": {"transport": transport},
    }

    c, _info = _cli_client.client_or_exit()
    with c:
        r = c.post("/resources", json=payload)
        if r.status_code == 409:
            typer.echo(f"server {name!r} already exists", err=True)
            raise typer.Exit(5)
        if r.status_code == 400:
            typer.echo(r.json()["error"]["message"], err=True)
            raise typer.Exit(6)
        if r.status_code == 422:
            typer.echo(f"config invalid: {r.json()['error']}", err=True)
            raise typer.Exit(6)
        _cli_client.check(r, verbose=verbose)
        uid = r.json()["uid"]
        typer.echo(f"registered: mcp_server {name}")
        settle(c, pending_for(c, uid, verbose=verbose), wait=wait, verbose=verbose)


def _transport(item: dict[str, Any]) -> str:
    return str((item.get("config") or {}).get("transport", {}).get("type", "?"))


register_kind_verbs(
    app,
    KindVerbs(
        kind="mcp_server",
        noun="MCP server",
        verbs=DEFAULT_VERBS | {"scope"},
        name_fixed=True,
        titled=False,
        edit_flags=MCP_EDIT_FLAGS,
        columns=(
            Column("Transport", _transport),
            Column("Description", lambda item: item.get("description") or ""),
        ),
        help={
            "list": "List every registered MCP server.",
            "show": "Show one MCP server, by name or uid.",
            "edit": (
                "Change an MCP server's description, transport, env, headers,"
                " secret refs or timeouts (its name is fixed). Only the options"
                " given change."
            ),
            "rm": "Remove an MCP server registration.",
        },
    ),
)


def _error_message(r: httpx.Response) -> str:
    try:
        return str(r.json()["error"]["message"])
    except Exception:
        return f"HTTP {r.status_code}"


def _capabilities_line(r: httpx.Response) -> str:
    if r.status_code != 200:
        return f"capabilities: not re-queried ({_error_message(r)})"
    data = r.json()
    counts = ", ".join(
        f"{len(data.get(plural) or [])} {plural}" for plural in ("tools", "prompts", "resources")
    )
    if data.get("from_cache"):
        return f"capabilities: {counts} (last known — the upstream did not answer)"
    return f"capabilities: {counts} (re-queried)"


@app.command("test")
def test_cmd(
    ctx: typer.Context,
    name: str = typer.Argument(..., help="Server name"),
) -> None:
    """Re-query a server's capabilities, then report whether it answers.

    Exits 7 when the server does not answer.

    \f
    Routes: ``POST /resources/mcp_server/{uid}/refresh`` then ``.../test``
    (spec mcp-gateway "Manage MCP servers as resources"). The refresh's own
    failure is reported, not fatal: an unreachable upstream is exactly what the
    health test that follows is there to name.
    """
    verbose = verbose_of(ctx)
    c, _info = _cli_client.client_or_exit()
    with c:
        uid = resolve_uid(c, "mcp_server", name, verbose=verbose)
        refreshed = c.post(f"/resources/mcp_server/{uid}/refresh")
        if refreshed.status_code == 404:
            _cli_client.check(refreshed, verbose=verbose)
        r = c.post(f"/resources/mcp_server/{uid}/test")
        _cli_client.check(r, verbose=verbose)
    typer.echo(_capabilities_line(refreshed))
    data = r.json()
    if data["ok"]:
        typer.echo(f"OK  ({data['latency_ms']} ms)")
    else:
        typer.echo(f"FAIL ({data['latency_ms']} ms): {data.get('error_message')}", err=True)
        raise typer.Exit(7)


app.add_typer(cap_app, name="cap")
