"""Value objects for the knowledge layer.

Everything here describes what is on disk. Nothing is persisted: a catalogue
is produced by walking the directory at call time, so these types are the
shape of an answer, never the shape of a row.
"""

from __future__ import annotations

from dataclasses import dataclass, field

ACTOR_AGENT = "agent"
ACTOR_USER = "user"


@dataclass(frozen=True)
class CollectionEntry:
    """One collection, as the top level of the catalogue shows it.

    ``pending_count`` is the material still waiting in the collection's inbox
    to be merged — what an agent cannot read yet (spec knowledge FR-005).
    """

    #: The collection resource's identity. Every route that addresses this
    #: collection takes it, so the catalogue has to carry it — the page cannot
    #: derive it from a name any more, and asking per row would be the N+1 the
    #: catalogue exists to avoid.
    #:
    #: Empty for a directory on disk that no row claims: the catalogue is
    #: generated by walking the tree, so it can see such a folder, and the
    #: enabled-rows filter is what keeps one out of the list a caller gets.
    uid: str
    name: str
    #: First paragraph of the collection's ``README.md``; empty when absent.
    description: str
    document_count: int = 0
    pending_count: int = 0


@dataclass(frozen=True)
class DirectoryEntry:
    """A subdirectory inside a collection — filed by a person or by curation."""

    #: Path relative to the knowledge root, e.g. ``shopee/account``.
    path: str
    name: str
    file_count: int


@dataclass(frozen=True)
class FileEntry:
    """A file as the catalogue lists it: enough to choose without reading."""

    #: Path relative to the knowledge root, e.g. ``shopee/account/gateway.md``.
    path: str
    title: str
    description: str
    actor: str
    updated_at: str


@dataclass(frozen=True)
class CatalogueLevel:
    """One level of one collection — what a human surface pages through."""

    path: str
    directories: tuple[DirectoryEntry, ...] = field(default_factory=tuple)
    files: tuple[FileEntry, ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class KnowledgeFile:
    """A file's full content plus the on-disk truth a surface must expose."""

    path: str
    title: str
    description: str
    actor: str
    created_at: str
    updated_at: str
    body: str
    #: Absolute path of the ``.md`` file (spec knowledge FR-041).
    file_path: str
    #: Absolute path of its containing folder.
    folder_path: str
    #: When curation last had this document in front of it; empty when it
    #: never has (FR-028).
    curated_at: str = ""


@dataclass(frozen=True)
class GrepMatch:
    path: str
    line_number: int
    line: str


@dataclass(frozen=True)
class GrepOutcome:
    matches: tuple[GrepMatch, ...] = field(default_factory=tuple)
    truncated: bool = False


@dataclass(frozen=True)
class Pending:
    """One item a pass can take: inbox material, or an edited document.

    Exactly one field is set. ``material`` is the inbox item's file name —
    never a path a caller could aim elsewhere, since the inbox is not
    addressable from outside this layer; ``document`` is a
    knowledge-root-relative document path.
    """

    material: str | None = None
    document: str | None = None
