"""Value objects for the knowledge layer.

Everything here describes what is on disk. Nothing is persisted: a catalogue
is produced by walking the directory at call time, so these types are the
shape of an answer, never the shape of a row.
"""

from __future__ import annotations

from dataclasses import dataclass, field

ACTOR_AGENT = "agent"
ACTOR_USER = "user"


@dataclass(frozen=True)
class CollectionEntry:
    """One collection, as the top level of the catalogue shows it.

    ``document_count`` is the Markdown documents an agent can read.
    """

    #: The collection resource's identity. Every route that addresses this
    #: collection takes it, so the catalogue has to carry it — the page cannot
    #: derive it from a name any more, and asking per row would be the N+1 the
    #: catalogue exists to avoid.
    #:
    #: Empty for a directory on disk that no row claims: the catalogue is
    #: generated by walking the tree, so it can see such a folder, and the
    #: registry join is what keeps one out of the list a caller gets.
    uid: str
    name: str
    #: First paragraph of the collection's ``README.md``; empty when absent.
    description: str
    document_count: int = 0
    #: The collection directory's absolute path, so a surface can reveal it
    #: ("Return absolute paths on reads"); empty where it was not read.
    folder_path: str = ""
    #: When a document in the collection was last written (ISO 8601, UTC);
    #: ``None`` when it holds none.
    updated_at: str | None = None


@dataclass(frozen=True)
class DirectoryEntry:
    """A subdirectory inside a collection — filed by a person or an agent."""

    #: Path relative to the knowledge root, e.g. ``shopee/account``.
    path: str
    name: str
    file_count: int


@dataclass(frozen=True)
class FileEntry:
    """A file as the catalogue lists it: enough to choose without reading."""

    #: Path relative to the knowledge root, e.g. ``shopee/account/gateway.md``.
    path: str
    title: str
    description: str
    actor: str
    updated_at: str


@dataclass(frozen=True)
class CatalogueLevel:
    """One level of one collection — what a human surface pages through."""

    path: str
    directories: tuple[DirectoryEntry, ...] = field(default_factory=tuple)
    files: tuple[FileEntry, ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class KnowledgeFile:
    """A file's full content plus the on-disk truth a surface must expose."""

    path: str
    title: str
    description: str
    actor: str
    created_at: str
    updated_at: str
    body: str
    #: Absolute path of the ``.md`` file (spec knowledge "Return absolute paths
    #: on reads").
    file_path: str
    #: Absolute path of its containing folder.
    folder_path: str
    #: sha256 hex of the file's bytes as read — what an edit hands back so a
    #: file changed on disk since is refused rather than overwritten (spec
    #: knowledge "Save a document edited in the web UI").
    fingerprint: str = ""


@dataclass(frozen=True)
class GrepMatch:
    path: str
    line_number: int
    line: str


@dataclass(frozen=True)
class GrepOutcome:
    matches: tuple[GrepMatch, ...] = field(default_factory=tuple)
    truncated: bool = False


@dataclass(frozen=True)
class Submission:
    """What became of one piece of submitted material: the document it became."""

    collection: str
    title: str
    document: KnowledgeFile
