"""Value objects for the knowledge layer.

Everything here describes what is on disk. Nothing is persisted: a catalogue
is produced by walking the directory at call time, so these types are the
shape of an answer, never the shape of a row.
"""

from __future__ import annotations

from dataclasses import dataclass, field

ACTOR_AGENT = "agent"
ACTOR_USER = "user"


@dataclass(frozen=True)
class CollectionEntry:
    """One collection, as the top level of the catalogue shows it."""

    #: The collection resource's identity. Every route that addresses this
    #: collection takes it, so the catalogue has to carry it — the page cannot
    #: derive it from a name any more, and asking per row would be the N+1 the
    #: catalogue exists to avoid.
    #:
    #: Empty for a directory on disk that no row claims: the catalogue is
    #: generated by walking the tree, so it can see such a folder, and the
    #: registry join is what keeps one out of the list a caller gets.
    uid: str
    name: str
    #: First paragraph of the collection's ``README.md``; empty when absent.
    description: str
    #: Pages under ``pages/`` and sources under ``sources/`` (spec knowledge
    #: "Keep sources and pages apart in each collection").
    page_count: int = 0
    source_count: int = 0
    #: Sources no page cites and none marks skipped ("Derive which sources wait
    #: from the pages that cite them").
    waiting_source_count: int = 0
    #: Every mechanical finding ("Check a collection mechanically on every read").
    finding_count: int = 0
    findings: tuple[Finding, ...] = ()
    #: The collection directory's absolute path, so a surface can reveal it
    #: ("Return absolute paths on reads"); empty where it was not read.
    folder_path: str = ""
    #: When a document in the collection was last written (ISO 8601, UTC);
    #: ``None`` when it holds none.
    updated_at: str | None = None


@dataclass(frozen=True)
class DirectoryEntry:
    """A subdirectory inside a collection — filed by a person or an agent."""

    #: Path relative to the knowledge root, e.g. ``shopee/account``.
    path: str
    name: str
    file_count: int


@dataclass(frozen=True)
class FileEntry:
    """A file as the catalogue lists it: enough to choose without reading."""

    #: Path relative to the knowledge root, e.g. ``shopee/pages/gateway.md``.
    path: str
    title: str
    description: str
    actor: str
    updated_at: str
    #: ``page``, ``source`` or ``file`` (``paths.kind_of``).
    kind: str = "file"
    #: A page's ``type``; empty otherwise.
    page_type: str = ""
    #: A source no page cites and none marks skipped.
    waiting: bool = False


@dataclass(frozen=True)
class CatalogueLevel:
    """One level of one collection — what a human surface pages through."""

    path: str
    directories: tuple[DirectoryEntry, ...] = field(default_factory=tuple)
    files: tuple[FileEntry, ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class SourceRef:
    """A page's ``sources`` entry: the slug it names and the source it resolves
    to, ``path`` ``None`` when it names none."""

    slug: str
    path: str | None = None
    title: str = ""


@dataclass(frozen=True)
class LinkRef:
    """A ``[[target]]`` in a page's body and the one file it resolves to;
    ``path`` ``None`` when it is dead or ambiguous (``ambiguous`` says which)."""

    target: str
    path: str | None = None
    ambiguous: bool = False


@dataclass(frozen=True)
class PageRef:
    """A page, as a source names the pages that cite it."""

    path: str
    title: str


@dataclass(frozen=True)
class Finding:
    """One mechanical finding about a collection (spec knowledge "Check a
    collection mechanically on every read").

    ``path`` is the file it concerns; ``target`` the link or source it names,
    where it names one; ``others`` the other files a duplicate or an ambiguous
    link involves.
    """

    kind: str
    path: str
    target: str | None = None
    others: tuple[str, ...] = ()


@dataclass(frozen=True)
class KnowledgeFile:
    """A file's full content plus the on-disk truth a surface must expose."""

    path: str
    title: str
    description: str
    actor: str
    created_at: str
    updated_at: str
    body: str
    #: Absolute path of the ``.md`` file (spec knowledge "Return absolute paths
    #: on reads").
    file_path: str
    #: Absolute path of its containing folder.
    folder_path: str
    #: ``page``, ``source`` or ``file`` (``paths.kind_of``).
    kind: str = "file"
    #: A page's ``type`` and ``aliases``.
    page_type: str = ""
    aliases: tuple[str, ...] = ()
    #: A page's ``sources`` entries, each resolved to the source it names.
    sources: tuple[SourceRef, ...] = ()
    #: A page's ``[[links]]``, each resolved to the file it names.
    links: tuple[LinkRef, ...] = ()
    #: A source's pages that cite it, and whether it waits.
    cited_by: tuple[PageRef, ...] = ()
    waiting: bool = False


@dataclass(frozen=True)
class GrepMatch:
    path: str
    line_number: int
    line: str


@dataclass(frozen=True)
class GrepOutcome:
    matches: tuple[GrepMatch, ...] = field(default_factory=tuple)
    truncated: bool = False


@dataclass(frozen=True)
class Submission:
    """What became of one piece of submitted material: the document it became."""

    collection: str
    title: str
    document: KnowledgeFile
