"""Application layer for the one ``knowledge`` resource kind.

A collection of markdown files, a catalogue generated by walking them, and
ripgrep. There is no retrieval facade and no reindex routine to re-export,
because there is no index (spec knowledge FR-001).
"""

from coffer.application.knowledge.builtin_tools import register_knowledge_builtin_tools
from coffer.application.knowledge.kind import make_knowledge_kind
from coffer.application.knowledge.service import KIND_KNOWLEDGE, KnowledgeService

__all__ = [
    "KIND_KNOWLEDGE",
    "KnowledgeService",
    "make_knowledge_kind",
    "register_knowledge_builtin_tools",
]
