"""The knowledge layer's one service.

Every operation resolves to a filesystem operation over
``~/.coffer/knowledge/``. What this layer adds on top of the directory is two
things: **which collections the caller may see** (spec knowledge FR-010), and
**which lane a caller may write** (FR-013, FR-021).

The first is enforced here and, for agents, at delivery: a collection an agent
is not activated for never appears in the skill Coffer renders for it, so the
agent is never told the path. That is non-disclosure, not access control
(FR-012): an agent holding shell tools can read the directory itself. It
prevents mistaken retrieval, not deliberate access — which was equally true of
the tool-surface enforcement it replaces.

The second is why every write here names its lane. Nothing in this module can
write ``topics/``; that belongs to ``application.knowledge.curate``.
"""

from __future__ import annotations

import pathlib

from coffer.application.audit_service import AuditService
from coffer.application.resource_service import ResourceService
from coffer.domain.audit import AuditEventType
from coffer.domain.knowledge.entry import (
    ACTOR_AGENT,
    CatalogueLevel,
    CollectionEntry,
    FileEntry,
    GrepOutcome,
    KnowledgeFile,
)
from coffer.domain.knowledge.errors import (
    CollectionExists,
    CollectionNotFound,
    UnsafeKnowledgePath,
)
from coffer.domain.resource import ResourceRef
from coffer.domain.scope import is_active
from coffer.infrastructure.knowledge import catalogue, fs, paths
from coffer.infrastructure.knowledge.grep import DEFAULT_MAX_MATCHES, RipgrepSearch

KIND_KNOWLEDGE = "knowledge"


class KnowledgeService:
    def __init__(
        self,
        *,
        resources: ResourceService,
        audit: AuditService,
        search: RipgrepSearch | None = None,
    ) -> None:
        self._resources = resources
        self._audit = audit
        self._search = search or RipgrepSearch()

    # ----- collections -------------------------------------------------

    async def visible_collections(self, agent: str | None) -> list[str]:
        """The collections ``agent`` may be told about, in name order."""
        registered = await self._resources.list(kind=KIND_KNOWLEDGE, enabled=True)
        return sorted(r.name for r in registered if is_active(r.scope, agent))

    async def require_visible(self, relpath: str, agent: str | None) -> str:
        """The collection ``relpath`` names, once confirmed visible to ``agent``."""
        collection = paths.collection_of(relpath)
        if collection not in await self.visible_collections(agent):
            raise CollectionNotFound(collection)
        return collection

    async def create_collection(
        self,
        name: str,
        *,
        actor: str,
        description: str | None = None,
    ) -> CollectionEntry:
        """Register a collection, create its directory and both lanes.

        Deliberate creation is the whole point (FR-008): nothing here is
        reachable from a read or a write, so a typo cannot conjure a collection.
        """
        directory = paths.collection_dir(name)
        if directory.exists():
            raise CollectionExists(name)
        await self._resources.register(
            kind=KIND_KNOWLEDGE,
            name=name,
            config={},
            actor=actor,
            # Deliberately not the description (FR-011): for this kind it lives
            # in the collection's own README, where the person browsing the
            # folder can see and change it. A copy in the row would be written
            # once, read by nothing, and wrong the moment they edited the file.
            allow_lifecycle_kind=True,
        )
        fs.create_collection_dir(name)
        if description:
            paths.readme_path(name).write_text(f"# {name}\n\n{description}\n", encoding="utf-8")
        return CollectionEntry(name=name, description=catalogue.readme_description(name))

    async def list_collections(self, agent: str | None = None) -> list[CollectionEntry]:
        visible = set(await self.visible_collections(agent))
        return [c for c in catalogue.list_collections() if c.name in visible]

    # ----- reading, for the human surfaces -----------------------------

    async def list_level(self, relpath: str, agent: str | None = None) -> CatalogueLevel:
        """One level of one lane, generated by walking the directory.

        This serves the web page and the CLI. It is **not** an agent's
        retrieval path — an agent reads the files themselves at the absolute
        paths its delivered skill carries (FR-033, FR-037).
        """
        await self.require_visible(relpath, agent)
        return catalogue.list_level(relpath)

    async def read(self, relpath: str, agent: str | None = None) -> KnowledgeFile:
        await self.require_visible(relpath, agent)
        return fs.read_file(relpath)

    async def catalogue(
        self, agent: str | None = None
    ) -> list[tuple[CollectionEntry, tuple[FileEntry, ...]]]:
        """Every visible collection with its whole ``topics/`` lane.

        The one place the corpus is read all at once. It exists for skill
        rendering (FR-037), where handing the agent the entire catalogue is the
        point — the alternative, a level at a time through a tool, is what 448
        sessions demonstrated an agent never reaches for.
        """
        visible = set(await self.visible_collections(agent))
        return [
            (entry, catalogue.walk_files(paths.topics_dir(entry.name)))
            for entry in catalogue.list_collections()
            if entry.name in visible
        ]

    # ----- writing the sources lane ------------------------------------

    async def write_source(
        self,
        *,
        title: str,
        description: str,
        body: str,
        collection: str | None = None,
        folder: str | None = None,
        relpath: str | None = None,
        actor_kind: str = ACTOR_AGENT,
        actor: str,
        agent: str | None = None,
    ) -> KnowledgeFile:
        """Create a source in a collection, or replace the one at ``relpath``.

        ``collection`` plus an optional ``folder`` is what a caller names; the
        ``sources/`` segment is this layer's, not theirs, so no surface has to
        spell it and no caller can aim at the other lane by spelling it wrong.
        """
        if relpath is not None:
            target_collection = await self.require_visible(relpath, agent)
            paths.require_lane(relpath, expected=paths.SOURCES_DIR_NAME)
            directory = None
        elif collection:
            target_collection = await self.require_visible(collection, agent)
            directory = paths.lane_relpath(
                target_collection, paths.SOURCES_DIR_NAME, *(folder or "").strip("/").split("/")
            )
        else:
            raise UnsafeKnowledgePath("", "a write needs a collection or a path")
        written = fs.write_file(
            directory=directory or "",
            title=title,
            description=description,
            body=body,
            actor=actor_kind,
            relpath=relpath,
        )
        await self._audit.record(
            AuditEventType.KNOWLEDGE_WRITTEN.value,
            ref=ResourceRef(KIND_KNOWLEDGE, target_collection),
            actor=actor,
            details={"path": written.path},
        )
        return written

    async def delete_source(self, relpath: str, *, actor: str, agent: str | None = None) -> None:
        """Remove a source. A person's action — no agent-facing tool deletes."""
        collection = await self.require_visible(relpath, agent)
        paths.require_lane(relpath, expected=paths.SOURCES_DIR_NAME)
        fs.delete_file(relpath)
        await self._audit.record(
            AuditEventType.KNOWLEDGE_DELETED.value,
            ref=ResourceRef(KIND_KNOWLEDGE, collection),
            actor=actor,
            details={"path": relpath},
        )

    # ----- candidate selection, for curation ---------------------------

    async def match_topics(
        self,
        pattern: str,
        *,
        collection: str,
        max_matches: int = DEFAULT_MAX_MATCHES,
    ) -> GrepOutcome:
        """Literal matches inside one collection's ``topics/`` lane.

        Ripgrep survives the removal of ``coffer__grep`` as an *internal*
        mechanism: it is how a curation pass finds which existing documents a
        new source might belong to (FR-023). It is not reachable by any caller
        outside this process.
        """
        roots: list[pathlib.Path] = [paths.topics_dir(collection)]
        return await self._search.grep(roots, pattern, max_matches=max_matches)

    # ----- lifecycle ---------------------------------------------------

    async def cleanup_collection(self, name: str) -> None:
        """Remove a collection's directory when its Resource is deleted."""
        fs.remove_collection_dir(name)
