"""The knowledge layer's one service.

Every operation resolves to a filesystem operation over
``~/.coffer/knowledge/``. What this layer adds on top of the directory is
exactly one thing: **which collections the caller may see** (spec knowledge
FR-012). A collection is a Resource, so the framework's per-agent scope
decides, and this service is the enforcement point for it.

That enforcement is a convention, not a security boundary (FR-014): an agent
holding shell tools can read the directory itself. It prevents mistaken
retrieval, not deliberate access.
"""

from __future__ import annotations

import pathlib

from coffer.application.audit_service import AuditService
from coffer.application.resource_service import ResourceService
from coffer.domain.audit import AuditEventType
from coffer.domain.knowledge.entry import (
    ACTOR_AGENT,
    CatalogueLevel,
    CollectionEntry,
    GrepOutcome,
    KnowledgeFile,
)
from coffer.domain.knowledge.errors import (
    CollectionExists,
    CollectionNotFound,
    UnsafeKnowledgePath,
)
from coffer.domain.resource import ResourceRef
from coffer.domain.scope import agent_in_scope
from coffer.infrastructure.knowledge import fs, paths
from coffer.infrastructure.knowledge.grep import DEFAULT_MAX_MATCHES, RipgrepSearch

KIND_KNOWLEDGE = "knowledge"


class KnowledgeService:
    def __init__(
        self,
        *,
        resources: ResourceService,
        audit: AuditService,
        search: RipgrepSearch | None = None,
    ) -> None:
        self._resources = resources
        self._audit = audit
        self._search = search or RipgrepSearch()

    # ----- collections -------------------------------------------------

    async def visible_collections(self, agent: str | None) -> list[str]:
        """The collections ``agent`` may read, in name order.

        An agent's calls span every collection activated for it — there is no
        rule that leaves one out of a default (FR-012), because a collection an
        agent is authorized for but never searches is the death the named
        collections of the previous design died.
        """
        registered = await self._resources.list(kind=KIND_KNOWLEDGE, enabled=True)
        return sorted(r.name for r in registered if agent_in_scope(r.scope, agent))

    async def require_visible(self, relpath: str, agent: str | None) -> str:
        """The collection ``relpath`` names, once confirmed visible to ``agent``."""
        collection = paths.collection_of(relpath)
        if collection not in await self.visible_collections(agent):
            raise CollectionNotFound(collection)
        return collection

    async def create_collection(
        self,
        name: str,
        *,
        actor: str,
        description: str | None = None,
    ) -> CollectionEntry:
        """Register a collection and create its directory.

        Deliberate creation is the whole point (FR-010): nothing here is
        reachable from a read or a write, so a typo cannot conjure a collection.
        """
        try:
            directory = paths.collection_dir(name)
        except UnsafeKnowledgePath:
            raise
        if directory.exists():
            raise CollectionExists(name)
        await self._resources.register(
            kind=KIND_KNOWLEDGE,
            name=name,
            config={},
            actor=actor,
            description=description,
            allow_lifecycle_kind=True,
        )
        fs.create_collection_dir(name)
        if description:
            paths.readme_path(name).write_text(f"# {name}\n\n{description}\n", encoding="utf-8")
        return CollectionEntry(
            name=name,
            description=fs.readme_description(name),
            file_count=0,
        )

    async def list_collections(self, agent: str | None = None) -> list[CollectionEntry]:
        visible = set(await self.visible_collections(agent))
        return [c for c in fs.list_collections() if c.name in visible]

    # ----- catalogue and retrieval -------------------------------------

    async def list_level(self, relpath: str, agent: str | None = None) -> CatalogueLevel:
        """One level of the catalogue, generated by walking the directory."""
        await self.require_visible(relpath, agent)
        return fs.list_level(relpath)

    async def read(self, relpath: str, agent: str | None = None) -> KnowledgeFile:
        await self.require_visible(relpath, agent)
        return fs.read_file(relpath)

    async def grep(
        self,
        pattern: str,
        *,
        agent: str | None = None,
        collection: str | None = None,
        max_matches: int = DEFAULT_MAX_MATCHES,
    ) -> GrepOutcome:
        visible = await self.visible_collections(agent)
        if collection is not None:
            if collection not in visible:
                raise CollectionNotFound(collection)
            visible = [collection]
        roots: list[pathlib.Path] = [paths.collection_dir(name) for name in visible]
        return await self._search.grep(roots, pattern, max_matches=max_matches)

    # ----- writing -----------------------------------------------------

    async def write(
        self,
        *,
        title: str,
        description: str,
        body: str,
        directory: str | None = None,
        relpath: str | None = None,
        actor_kind: str = ACTOR_AGENT,
        actor: str,
        agent: str | None = None,
    ) -> KnowledgeFile:
        """Create a file, or replace the one at ``relpath``."""
        target = relpath or directory
        if not target:
            raise UnsafeKnowledgePath("", "a write needs a collection or a path")
        collection = await self.require_visible(target, agent)
        written = fs.write_file(
            directory=directory or "",
            title=title,
            description=description,
            body=body,
            actor=actor_kind,
            relpath=relpath,
        )
        await self._audit.record(
            AuditEventType.KNOWLEDGE_WRITTEN.value,
            ref=ResourceRef(KIND_KNOWLEDGE, collection),
            actor=actor,
            details={"path": written.path},
        )
        return written

    async def delete(self, relpath: str, *, actor: str, agent: str | None = None) -> None:
        collection = await self.require_visible(relpath, agent)
        fs.delete_file(relpath)
        await self._audit.record(
            AuditEventType.KNOWLEDGE_DELETED.value,
            ref=ResourceRef(KIND_KNOWLEDGE, collection),
            actor=actor,
            details={"path": relpath},
        )

    # ----- lifecycle ---------------------------------------------------

    async def cleanup_collection(self, name: str) -> None:
        """Remove a collection's directory when its Resource is deleted."""
        fs.remove_collection_dir(name)
