#!/usr/bin/env python3
"""Generate every capability's wire contract from the daemon's own OpenAPI document.

The contract direction (Principles, "II. Spec-as-Truth" → Contract direction;
ADR wire-contract-generated-from-the-pydantic-models) is Pydantic models →
this generator → ``openspec/specs/<capability>/contracts/api.openapi.yaml`` →
the frontend's generated types. This script is the middle arrow.

It builds the app exactly as ``docs-site/scripts/gen_rest_reference.py`` does
(``create_app().openapi()``: no lifespan, no port, no database, nothing under
``~/.coffer``), splits the document by :data:`OWNERS` — which capability owns
each route — and writes one file per capability holding its operations and
every schema they reach, nothing else. Output is deterministic: mapping keys
are sorted at every depth, lists keep the order the models give them, and
nothing depends on the time, the machine or the home directory. That is what
lets ``--check`` (run by ``make lint``) fail CI when a checked-in contract is
not what the models produce.

Ownership is also the route-coverage gate: a served route no rule claims, a
rule that claims nothing and a capability left with no route all fail
generation, so a new route cannot ship without an owning spec.

    .venv/bin/python scripts/gen_contracts.py           # rewrite the contracts (make contracts)
    .venv/bin/python scripts/gen_contracts.py --check   # exit 1 naming each stale file
"""

from __future__ import annotations

import logging
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
SPECS_DIR = REPO_ROOT / "openspec" / "specs"
CONTRACT_NAME = Path("contracts") / "api.openapi.yaml"

sys.path.insert(0, str(REPO_ROOT / "backend"))

#: Which capability owns each route, as ``(path prefix, capability)``. A path
#: belongs to the rule whose prefix matches the most leading path segments, so
#: a narrower rule carves a sub-tree out of a wider one — skill-manager owns an
#: agent's unmanaged skills inside agent-registry's ``/api/v1/agents``. A
#: capability is its folder path under ``openspec/specs/``.
OWNERS: tuple[tuple[str, str], ...] = (
    ("/api/v1/agent-providers", "chat"),
    ("/api/v1/agent-providers/{agent_key}/models", "agent-registry"),
    ("/api/v1/agents", "agent-registry"),
    ("/api/v1/agents/{uid}/unmanaged-skills", "skill-manager"),
    ("/api/v1/attention", "resource-framework"),
    ("/api/v1/audit", "resource-framework"),
    ("/api/v1/channels", "channels"),
    ("/api/v1/chat", "chat"),
    ("/api/v1/clis", "skill-manager"),
    ("/api/v1/credentials", "secret"),
    ("/api/v1/custom-tools", "mcp-gateway"),
    ("/api/v1/daemon", "daemon"),
    ("/api/v1/events", "resource-framework"),
    ("/api/v1/fs", "daemon"),
    ("/api/v1/storage", "daemon"),
    ("/api/v1/internal-engine-config", "internal-engine"),
    ("/api/v1/knowledge", "knowledge"),
    ("/api/v1/mcp", "mcp-gateway"),
    ("/api/v1/memory", "memory"),
    ("/api/v1/models", "provider-switching"),
    ("/api/v1/providers", "provider-switching"),
    ("/api/v1/proxy", "provider-switching"),
    ("/api/v1/reconcile", "resource-framework"),
    ("/api/v1/resources", "resource-framework"),
    ("/api/v1/resources/mcp_server", "mcp-gateway"),
    ("/api/v1/retention", "resource-framework"),
    ("/api/v1/settings", "secret"),
    ("/api/v1/skills", "skill-manager"),
    ("/api/v1/sync", "vault-sync"),
    ("/api/v1/upkeep", "resource-framework"),
    ("/api/v1/usage", "provider-switching"),
)

#: Served paths that are deliberately in no REST contract: ``/mcp`` is the MCP
#: protocol endpoint, a JSON-RPC surface whose contract is the MCP
#: specification itself.
UNCONTRACTED: frozenset[str] = frozenset({"/mcp"})

#: The title each contract carries.
TITLES: dict[str, str] = {
    "agent-registry": "Agent Registry",
    "channels": "Channels",
    "chat": "Chat",
    "daemon": "Daemon",
    "internal-engine": "Internal Engine",
    "knowledge": "Knowledge",
    "mcp-gateway": "MCP Gateway",
    "memory": "Memory",
    "provider-switching": "Provider Switching",
    "resource-framework": "Resource Framework",
    "secret": "Secrets",
    "skill-manager": "Skill Manager",
    "vault-sync": "Vault Sync",
}

HEADER = (
    "# GENERATED by `make contracts` (scripts/gen_contracts.py) from the daemon's\n"
    "# Pydantic models. Do not edit: change the models and regenerate.\n"
)

_DESCRIPTION = (
    "The {title} routes of Coffer's management API, generated from the daemon's "
    "Pydantic models. The behaviour behind them is this capability's spec.md; "
    "authentication, the error envelope and tracing are described once in the "
    "docs-site REST API reference. Every route except `GET /api/v1/daemon/status` "
    "requires the `X-Coffer-Token` header."
)

_METHODS = frozenset({"get", "put", "post", "delete", "options", "head", "patch", "trace"})
_SCHEMA_REF = "#/components/schemas/"


class OwnershipError(Exception):
    """The route table and :data:`OWNERS` disagree."""


def _segments(path: str) -> list[str]:
    return [part for part in path.split("/") if part]


def owner_of(path: str) -> str | None:
    """The capability owning ``path``: its longest segment-prefix rule."""
    parts = _segments(path)
    best: tuple[int, str] | None = None
    for prefix, capability in OWNERS:
        rule = _segments(prefix)
        if parts[: len(rule)] == rule and (best is None or len(rule) > best[0]):
            best = (len(rule), capability)
    return best[1] if best else None


def load_openapi() -> dict[str, Any]:
    """The daemon's OpenAPI document, built without starting the daemon."""
    from coffer.surfaces.http.app import create_app

    logging.disable(logging.CRITICAL)
    try:
        return create_app().openapi()
    finally:
        logging.disable(logging.NOTSET)


def split_paths(document: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """``{capability: {path: path item}}``, failing on any ownership gap."""
    owned: dict[str, dict[str, Any]] = {capability: {} for capability in TITLES}
    unowned: list[str] = []
    for path, item in (document.get("paths") or {}).items():
        if path in UNCONTRACTED:
            continue
        capability = owner_of(path)
        if capability is None:
            unowned.append(path)
            continue
        if capability not in owned:
            raise OwnershipError(f"OWNERS names {capability!r}, which TITLES does not list")
        owned[capability][path] = item

    problems: list[str] = [f"no capability owns {path}" for path in sorted(unowned)]
    served = {path for paths in owned.values() for path in paths}
    for prefix, capability in OWNERS:
        if not any(owner_of(path) == capability and _claims(prefix, path) for path in served):
            problems.append(f"the rule ({prefix!r}, {capability!r}) claims no served route")
    problems += [f"{capability} owns no route" for capability, paths in owned.items() if not paths]
    for capability in owned:
        if not (SPECS_DIR / capability / "spec.md").is_file():
            problems.append(f"{capability} has no spec at openspec/specs/{capability}/spec.md")
    if problems:
        raise OwnershipError(
            "the route table and OWNERS in scripts/gen_contracts.py disagree:\n  "
            + "\n  ".join(problems)
        )
    return owned


def _claims(prefix: str, path: str) -> bool:
    rule = _segments(prefix)
    return _segments(path)[: len(rule)] == rule


def _refs(node: Any) -> Iterator[str]:
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str) and ref.startswith(_SCHEMA_REF):
            yield ref[len(_SCHEMA_REF) :]
        for value in node.values():
            yield from _refs(value)
    elif isinstance(node, list):
        for value in node:
            yield from _refs(value)


def _reachable_schemas(paths: dict[str, Any], schemas: dict[str, Any]) -> dict[str, Any]:
    seen: dict[str, Any] = {}
    pending = list(_refs(paths))
    while pending:
        name = pending.pop()
        if name in seen:
            continue
        seen[name] = schemas[name]
        pending.extend(_refs(schemas[name]))
    return seen


def _sorted(node: Any) -> Any:
    if isinstance(node, dict):
        return {key: _sorted(node[key]) for key in sorted(node)}
    if isinstance(node, list):
        return [_sorted(value) for value in node]
    return node


def contract_for(
    capability: str, paths: dict[str, Any], document: dict[str, Any]
) -> dict[str, Any]:
    """One capability's OpenAPI document: its operations and what they reach."""
    operations = {
        path: {key: value for key, value in item.items() if key in _METHODS or key == "parameters"}
        for path, item in paths.items()
    }
    schemas = (document.get("components") or {}).get("schemas") or {}
    title = TITLES[capability]
    contract: dict[str, Any] = {
        "openapi": document["openapi"],
        "info": {
            "title": f"Coffer — {title} API",
            "version": document["info"]["version"],
            "description": _DESCRIPTION.format(title=title),
        },
        "servers": [{"url": "http://127.0.0.1:8000"}],
        "paths": _sorted(operations),
    }
    reachable = _reachable_schemas(operations, schemas)
    if reachable:
        contract["components"] = {"schemas": _sorted(reachable)}
    return contract


class _Dumper(yaml.SafeDumper):
    """Block style throughout; a multi-line string as a literal block."""


def _represent_str(dumper: yaml.SafeDumper, value: str) -> yaml.ScalarNode:
    style = "|" if "\n" in value else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)


_Dumper.add_representer(str, _represent_str)


def dump(contract: dict[str, Any]) -> str:
    body = yaml.dump(
        contract,
        Dumper=_Dumper,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=100_000,
    )
    return HEADER + body


def render() -> dict[Path, str]:
    """Every contract file's path and the text the models produce for it."""
    document = load_openapi()
    return {
        SPECS_DIR / capability / CONTRACT_NAME: dump(contract_for(capability, paths, document))
        for capability, paths in split_paths(document).items()
    }


def _checked_in() -> set[Path]:
    return set(SPECS_DIR.glob(f"**/{CONTRACT_NAME.as_posix()}"))


def main(argv: list[str]) -> int:
    try:
        rendered = render()
    except OwnershipError as exc:
        print(f"gen_contracts: {exc}", file=sys.stderr)
        return 1
    orphans = sorted(_checked_in() - set(rendered))
    if "--check" in argv:
        stale = [
            path
            for path, text in rendered.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != text
        ]
        for path in stale:
            print(
                f"gen_contracts: {path.relative_to(REPO_ROOT)} is not what the models "
                "produce — run `make contracts` and commit the result",
                file=sys.stderr,
            )
        for path in orphans:
            print(
                f"gen_contracts: {path.relative_to(REPO_ROOT)} is generated by nothing — "
                "delete it, or give its capability a route in OWNERS",
                file=sys.stderr,
            )
        return 1 if stale or orphans else 0
    for path, text in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    for path in orphans:
        path.unlink()
        print(f"deleted {path.relative_to(REPO_ROOT)} (no capability owns a route for it)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
