"""Generate docs-site/reference/cli.md from the Typer app.

The page is built by walking the real command tree (``typer.main.get_command``)
through click's introspection API, so every group, command, argument and
option on the page is one the CLI actually has. Output is deterministic: the
same code produces the same bytes, which is what lets
``scripts/check_cli_reference.py`` fail CI when the page drifts.

    .venv/bin/python docs-site/scripts/gen_cli_reference.py          # write the page
    .venv/bin/python docs-site/scripts/gen_cli_reference.py --stdout # print it
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT = REPO_ROOT / "docs-site" / "reference" / "cli.md"

sys.path.insert(0, str(REPO_ROOT / "backend"))

HEADER = """\
---
title: CLI reference
description: Every coffer command, argument and option, generated from the CLI itself.
---

# CLI reference

This page lists every `coffer` command group, command, argument and option. It is
generated from the CLI's own command tree, so it matches what `coffer <command> --help`
prints for the version on `main`.

::: info Generated page
Do not edit this file by hand. Regenerate it with `make docs-reference`
(which runs `docs-site/scripts/gen_cli_reference.py`); `make lint` fails when the
page and the CLI disagree.
:::

Most commands talk to the local daemon over its management API and start it if it is
not running. For the exit codes every command shares, see
[Error codes](/reference/error-codes#cli-exit-codes).
"""

_CODE_SPAN = re.compile(r"(``.+?``|`[^`]+`)")


def _escape_prose(text: str) -> str:
    """Make help text safe for VitePress: Markdown outside code spans cannot
    open HTML tags, Vue interpolations or emphasis by accident."""
    out: list[str] = []
    for i, part in enumerate(_CODE_SPAN.split(text)):
        if i % 2 == 1:
            out.append(part)
            continue
        part = part.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        part = part.replace("*", "\\*")
        # `{{` is a Vue interpolation even after entity decoding; code spans
        # are the only safe carrier.
        part = re.sub(r"(\{\{+|\}\}+)", r"`\1`", part)
        out.append(part)
    return "".join(out)


def _paragraphs(text: str) -> list[str]:
    """Split help text into Markdown paragraphs, joining wrapped lines."""
    text = text.split("\f", 1)[0]
    paras: list[str] = []
    for block in re.split(r"\n\s*\n", text.strip()):
        lines = [ln.rstrip() for ln in block.splitlines() if ln.strip() and ln.strip() != "\b"]
        if not lines:
            continue
        listy = any(re.match(r"\s*([-*•]|\d+[.)])\s", ln) for ln in lines)
        if listy:
            items: list[str] = []
            for ln in lines:
                stripped = ln.strip()
                if re.match(r"([-*•]|\d+[.)])\s", stripped) or not items:
                    items.append(re.sub(r"^[*•]\s", "- ", stripped))
                else:
                    items[-1] += " " + stripped
            paras.append(
                "\n".join(
                    _escape_prose(it) if not it.startswith("- ") else "- " + _escape_prose(it[2:])
                    for it in items
                )
            )
        else:
            paras.append(_escape_prose(" ".join(ln.strip() for ln in lines)))
    return paras


def _cell(text: str) -> str:
    """One table cell: a single line with pipes escaped."""
    flat = " ".join(" ".join(_paragraphs(text)).split())
    return flat.replace("|", "\\|") if flat else ""


def _is_unset(value: Any) -> bool:
    return value is None or "UNSET" in repr(value) or "Sentinel" in type(value).__name__


def _param_name(prm: Any) -> str:
    if prm.param_type_name == "argument":
        return f"`{(prm.metavar or prm.name).upper()}`"
    names = sorted(prm.opts, key=lambda o: (not o.startswith("--"), o))
    label = ", ".join(names)
    if prm.secondary_opts:
        label += " / " + ", ".join(prm.secondary_opts)
    return f"`{label}`"


def _param_type(prm: Any) -> str:
    if getattr(prm, "is_flag", False) and not prm.secondary_opts:
        return "flag"
    ptype = prm.type
    choices = getattr(ptype, "choices", None)
    if choices:
        return " \\| ".join(f"`{c}`" for c in choices)
    name = getattr(ptype, "name", "") or type(ptype).__name__
    name = name.lower()
    lo, hi = getattr(ptype, "min", None), getattr(ptype, "max", None)
    if lo is not None or hi is not None:
        name = (
            name.replace(" range", "") + f" ({'' if lo is None else lo}-{'' if hi is None else hi})"
        )
    if getattr(prm, "multiple", False) or (prm.nargs not in (1, 0) and prm.nargs is not None):
        name += " (repeatable)" if prm.param_type_name == "option" else " (variadic)"
    return name


def _param_default(prm: Any) -> str:
    if prm.required:
        return "required"
    default = prm.default
    if callable(default) or _is_unset(default):
        return ""
    if isinstance(default, bool):
        if getattr(prm, "is_flag", False) and not prm.secondary_opts and default is False:
            return ""
        return f"`{str(default).lower()}`"
    if isinstance(default, (list, tuple)):
        return "" if not default else f"`{', '.join(map(str, default))}`"
    text = str(default)
    return f"`{text}`" if text else '`""`'


def _usage(chain: list[tuple[str, Any]]) -> str:
    """The usage line click prints, for a command reached through ``chain``."""
    ctx = None
    for name, cmd in chain:
        ctx = cmd.context_class(cmd, info_name=name, parent=ctx)
    assert ctx is not None
    pieces = chain[-1][1].collect_usage_pieces(ctx)
    return " ".join([name for name, _ in chain] + pieces)


def _visible_params(cmd: Any) -> list[Any]:
    return [p for p in cmd.params if not getattr(p, "hidden", False)]


def _params_table(cmd: Any) -> list[str]:
    params = _visible_params(cmd)
    if not params:
        return []
    rows = ["| Name | Kind | Type | Default | Description |", "| --- | --- | --- | --- | --- |"]
    for prm in params:
        kind = "argument" if prm.param_type_name == "argument" else "option"
        help_text = getattr(prm, "help", None) or ""
        cells = (_param_name(prm), kind, _param_type(prm), _param_default(prm), _cell(help_text))
        rows.append("| " + " | ".join(cells) + " |")
    return [*rows, ""]


def _children(group: Any) -> list[tuple[str, Any]]:
    return [(n, c) for n, c in group.commands.items() if not getattr(c, "hidden", False)]


Chain = list[tuple[str, Any]]


def _command_block(chain: Chain) -> list[str]:
    cmd = chain[-1][1]
    lines = [f"### {' '.join(name for name, _ in chain[1:])}", ""]
    lines += ["```sh", _usage(chain), "```", ""]
    if getattr(cmd, "deprecated", False):
        lines += ["::: warning Deprecated", "This command is deprecated.", ":::", ""]
    for para in _paragraphs(cmd.help or cmd.short_help or ""):
        lines += [para, ""]
    lines += _params_table(cmd)
    if hasattr(cmd, "commands"):
        subs = _children(cmd)
        if subs:
            lines += ["Subcommands: " + ", ".join(f"`{n}`" for n, _ in subs) + ".", ""]
    return lines


def _walk_group(chain: Chain) -> list[str]:
    """Every command under a group, depth first, in declaration order."""
    out: list[str] = []
    for name, child in _children(chain[-1][1]):
        child_chain = [*chain, (name, child)]
        out += _command_block(child_chain)
        if hasattr(child, "commands"):
            out += _walk_group(child_chain)
    return out


def _first_sentence(text: str) -> str:
    paras = _paragraphs(text)
    if not paras:
        return ""
    head = re.split(r"(?<=[.!?])\s", paras[0], maxsplit=1)[0]
    return head.replace("|", "\\|")


def render() -> str:
    import typer

    from coffer.surfaces.cli.main import app

    root = typer.main.get_command(app)
    root_chain: Chain = [("coffer", root)]
    lines = [HEADER]
    lines += ["## Global options", ""]
    lines += ["```sh", _usage(root_chain), "```", ""]
    lines += _params_table(root)
    lines += ["## Command groups", ""]
    lines += ["| Group | Description |", "| --- | --- |"]
    for name, group in _children(root):
        summary = _first_sentence(group.help or group.short_help or "")
        lines.append(f"| [`coffer {name}`](#coffer-{name}) | {summary} |")
    lines.append("")
    for name, group in _children(root):
        chain = [*root_chain, (name, group)]
        lines += [f"## coffer {name}", ""]
        lines += ["```sh", _usage(chain), "```", ""]
        for para in _paragraphs(group.help or ""):
            lines += [para, ""]
        lines += _params_table(group)
        if hasattr(group, "commands"):
            lines += _walk_group(chain)
    text = "\n".join(lines)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if "--stdout" in argv:
        sys.stdout.write(text)
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
