"""The two ports the secret boundary stands on: its machine-local tables and
the encrypted store's slice it needs (spec secret "Keep the boundary's
bindings, approvals and switch on this machine")."""

from __future__ import annotations

import builtins
from datetime import datetime
from typing import Protocol

from coffer.domain.secrets import SecretApproval, SecretBinding


class BoundaryStorePort(Protocol):
    def get_binding(self, ref: str, kind: str, uid: str, slot: str) -> SecretBinding | None: ...
    def bindings(self, ref: str | None = None) -> builtins.list[SecretBinding]: ...
    def has_any_binding(self, ref: str) -> bool: ...
    def put_binding(self, binding: SecretBinding) -> None: ...
    def delete_bindings(self, ref: str) -> None: ...
    def create_approval(self, approval: SecretApproval) -> None: ...
    def get_approval(self, approval_id: str) -> SecretApproval | None: ...
    def find_open_bind(
        self, ref: str, kind: str, uid: str, slot: str, target_fingerprint: str
    ) -> SecretApproval | None: ...
    def pending_of_op(self, op: str, ref: str | None = None) -> list[SecretApproval]: ...
    def list_approvals(
        self, *, status: str | None = None, destination_uid: str | None = None, limit: int = 200
    ) -> list[SecretApproval]: ...
    def decide(
        self, approval_id: str, status: str, *, by: str, at: str, only_from: str = "pending"
    ) -> bool: ...
    def get_setting(self, key: str) -> str | None: ...
    def set_setting(self, key: str, value: str) -> None: ...


class SealedValueStorePort(Protocol):
    """The slice of the encrypted store the boundary needs."""

    def exists(self, ref: str) -> bool: ...
    def created_at(self, ref: str) -> datetime | None: ...
    def set(self, ref: str, value: str) -> None: ...


__all__ = ["BoundaryStorePort", "SealedValueStorePort"]
