"""Domain entities for the workflow layer (spec workflow).

Pure: the template's shape and its validation rules, the run and node state
machines, the closed event vocabulary and its projection fold. Nothing here
reads a clock, a database or a file — the application layer supplies all three.
"""

from coffer.domain.workflow.errors import (
    AttemptCeilingReached,
    IllegalTransition,
    NotThisMachine,
    RunTerminal,
    TemplateInvalid,
    WorkflowError,
    WorkflowVersionConflict,
)
from coffer.domain.workflow.events import (
    ActorKind,
    EventActor,
    EventType,
    RunProjection,
    WorkflowEvent,
    project,
)
from coffer.domain.workflow.run import (
    ADHOC_KEY_PREFIX,
    TERMINAL_APPROVAL_STATUSES,
    TERMINAL_NODE_STATUSES,
    TERMINAL_RUN_STATUSES,
    Approval,
    ApprovalKind,
    ApprovalStatus,
    FailureReason,
    NodeAction,
    NodeAttempt,
    NodeStatus,
    Run,
    RunInput,
    RunInputKind,
    RunSignal,
    RunStatus,
    is_adhoc_key,
)
from coffer.domain.workflow.template import (
    DEFAULT_ATTEMPT_CEILING,
    ApprovalPolicy,
    ArtifactSpec,
    FailureAction,
    FeedbackEdge,
    Node,
    NodeType,
    OnFailure,
    Stage,
    WorkflowTemplate,
    parse_template,
)
from coffer.domain.workflow.transitions import (
    FeedbackOutcome,
    NodePosition,
    allowed_node_actions,
    allowed_run_signals,
    apply_node_action,
    apply_run_signal,
    check_attempt_ceiling,
    ensure_owning_machine,
    ensure_run_mutable,
    ensure_version,
    next_node,
    resolve_feedback_edge,
    take_feedback_edge,
)

__all__ = [
    "ADHOC_KEY_PREFIX",
    "DEFAULT_ATTEMPT_CEILING",
    "TERMINAL_APPROVAL_STATUSES",
    "TERMINAL_NODE_STATUSES",
    "TERMINAL_RUN_STATUSES",
    "ActorKind",
    "Approval",
    "ApprovalKind",
    "ApprovalPolicy",
    "ApprovalStatus",
    "ArtifactSpec",
    "AttemptCeilingReached",
    "EventActor",
    "EventType",
    "FailureAction",
    "FailureReason",
    "FeedbackEdge",
    "FeedbackOutcome",
    "IllegalTransition",
    "Node",
    "NodeAction",
    "NodeAttempt",
    "NodePosition",
    "NodeStatus",
    "NodeType",
    "NotThisMachine",
    "OnFailure",
    "Run",
    "RunInput",
    "RunInputKind",
    "RunProjection",
    "RunSignal",
    "RunStatus",
    "RunTerminal",
    "Stage",
    "TemplateInvalid",
    "WorkflowError",
    "WorkflowEvent",
    "WorkflowTemplate",
    "WorkflowVersionConflict",
    "allowed_node_actions",
    "allowed_run_signals",
    "apply_node_action",
    "apply_run_signal",
    "check_attempt_ceiling",
    "ensure_owning_machine",
    "ensure_run_mutable",
    "ensure_version",
    "is_adhoc_key",
    "next_node",
    "parse_template",
    "project",
    "resolve_feedback_edge",
    "take_feedback_edge",
]
