// src/i18n/backend-keys.test.ts — guards that every backend error code and
// audit event type has a localized string in BOTH locales, so zh users never
// see a raw English/snake_case code on an error toast or audit row.
//
// The backend key sets come from a checked-in fixture generated by
// `scripts/dump_i18n_backend_keys.py` (run it after adding a CofferError
// subclass or AuditEventType). Diffing the locales against that fixture means a
// new untranslated code fails CI instead of silently shipping.
import { expect, test } from "vitest";

import backendKeys from "./backend-keys.fixture.json";
import en from "./locales/en.json";
import zh from "./locales/zh.json";

// Codes whose user-facing string is intentionally the daemon's own message,
// because that message carries actionable specifics a generic translation would
// drop (e.g. the exact secret name in ADOPT_SECRET_UNRESOLVED). These have no
// errors.<CODE> key; translateApiError falls back to the envelope message.
const MESSAGE_PASSTHROUGH = new Set<string>(["ADOPT_SECRET_UNRESOLVED"]);

const ERROR_CODES: string[] = backendKeys.errorCodes.filter((c) => !MESSAGE_PASSTHROUGH.has(c));
const AUDIT_EVENTS: string[] = backendKeys.auditEvents;

function missing(required: string[], have: Record<string, unknown>): string[] {
  return required.filter((k) => !(k in have)).sort();
}

test("every backend error code (except message-passthrough) has an errors.<CODE> key in en + zh", () => {
  expect(missing(ERROR_CODES, en.errors)).toEqual([]);
  expect(missing(ERROR_CODES, zh.errors)).toEqual([]);
});

test("every audit event type has an audit.activity.<event> key in en + zh", () => {
  expect(missing(AUDIT_EVENTS, en.audit.activity)).toEqual([]);
  expect(missing(AUDIT_EVENTS, zh.audit.activity)).toEqual([]);
});

test("errors.* maps carry no key the backend no longer emits", () => {
  const known = new Set(ERROR_CODES);
  // A reason-qualified key `errors.<CODE>_<reason>` (KB15) lets a machine
  // `IngestRejected` reason drive a specific message via translateApiError;
  // it is legitimate as long as its `<CODE>` prefix is a known backend code.
  const isKnownOrReasonQualified = (k: string) =>
    known.has(k) || ERROR_CODES.some((c) => k.startsWith(`${c}_`));
  const stale = (have: Record<string, unknown>) =>
    Object.keys(have)
      .filter((k) => !isKnownOrReasonQualified(k))
      .sort();
  expect(stale(en.errors)).toEqual([]);
  expect(stale(zh.errors)).toEqual([]);
});

test("audit.activity.* maps carry no key the backend no longer emits", () => {
  const known = new Set(AUDIT_EVENTS);
  const stale = (have: Record<string, unknown>) =>
    Object.keys(have).filter((k) => !known.has(k)).sort();
  expect(stale(en.audit.activity)).toEqual([]);
  expect(stale(zh.audit.activity)).toEqual([]);
});

test("audit.actor covers every actor the backend writes + every request origin", () => {
  // Request-origin actors (X-Coffer-Actor header) + the domain actors the
  // backend records directly on audit rows (audit_service.record(actor=...)).
  const actors = ["ui", "cli", "api", "system", "user", "agent", "channel"];
  expect(missing(actors, en.audit.actor)).toEqual([]);
  expect(missing(actors, zh.audit.actor)).toEqual([]);
});
